In [1]:
import numpy as np
from numpy import random as rand 

In [2]:
x = np.array(([2, 9], [1, 5], [3, 6]))
y = np.array(([92], [86], [89]))

x = x/np.amax(x, axis=0)
y = y/100

In [3]:
x,y

(array([[0.66666667, 1.        ],
        [0.33333333, 0.55555556],
        [1.        , 0.66666667]]),
 array([[0.92],
        [0.86],
        [0.89]]))

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))


def sigmoid_grad(x):
    return x*(1-x)

In [5]:
epoch=1000
eta=0.2

input_neurons=len(x[0])
hidden_neurons=3
output_neurons=len(y[0])

wh=rand.uniform(size=(input_neurons,hidden_neurons))
bh=rand.uniform(size=(1,hidden_neurons))

wout=rand.uniform(size=(hidden_neurons,output_neurons))
bout=rand.uniform(size=(1,output_neurons))

In [6]:
for _ in range(epoch):
    h_ip = np.dot(x, wh)+bh
    h_act = sigmoid(h_ip)

    o_ip = np.dot(h_act, wout)+bout
    o_act = sigmoid(o_ip)

    '''Back Propagation'''
    error_output = y-o_act
    out_grad = sigmoid_grad(o_act)
    d_output = out_grad * error_output

    error_hidden = d_output.dot(wout.T)
    hidden_grad = sigmoid_grad(h_act)
    d_hidden = error_hidden*hidden_grad

    wout = h_act.T.dot(d_output)*eta
    wh += x.T.dot(d_hidden)*eta

In [7]:
x,y,o_act

(array([[0.66666667, 1.        ],
        [0.33333333, 0.55555556],
        [1.        , 0.66666667]]),
 array([[0.92],
        [0.86],
        [0.89]]),
 array([[0.73539564],
        [0.73472776],
        [0.73549337]]))